import {
  Archive,
  ArchiveRestore,
  ArrowDown,
  ArrowLeft,
  ArrowUp,
  Building2,
  Check,
  ChevronDown,
  ChevronRight,
  ChevronsUpDown,
  Clock,
  Cloud,
  Copy,
  Download,
  Info,
  KeyRound,
  Languages,
  LayoutDashboard,
  LockKeyhole,
  LogOut,
  Menu,
  MonitorSmartphone,
  Palette,
  Pencil,
  Plus,
  RefreshCw,
  ShieldCheck,
  TabletSmartphone,
  Trash2,
  TriangleAlert,
  Users,
  WifiOff,
  X,
} from 'lucide-react'
import { cn } from '@/lib/utils'

const ICONS = {
  check: Check,
  x: X,
  alert: TriangleAlert,
  info: Info,
  cloud: Cloud,
  sync: RefreshCw,
  offline: WifiOff,
  chevron: ChevronDown,
  clock: Clock,
  up: ArrowUp,
  down: ArrowDown,
  dashboard: LayoutDashboard,
  organisation: Building2,
  users: Users,
  roles: ShieldCheck,
  appearance: Palette,
  sessions: MonitorSmartphone,
  security: LockKeyhole,
  menu: Menu,
  signOut: LogOut,
  language: Languages,
  updown: ChevronsUpDown,
  plus: Plus,
  copy: Copy,
  download: Download,
  chevronRight: ChevronRight,
  back: ArrowLeft,
  device: TabletSmartphone,
  edit: Pencil,
  archive: Archive,
  restore: ArchiveRestore,
  remove: Trash2,
  key: KeyRound,
}

/** Lucide line icon: 1.5 stroke, 16px in navigation, 18px in tools. Decorative only. */
export function Icon({ name, size = 16, className, ...rest }) {
  const Glyph = ICONS[name]
  if (!Glyph) return null
  return <Glyph size={size} strokeWidth={1.5} aria-hidden="true" focusable="false" className={cn('shrink-0', className)} {...rest} />
}
