import {
  Archive,
  ArchiveRestore,
  ArrowDown,
  ArrowLeft,
  ArrowLeftRight,
  ArrowUp,
  Bell,
  Building2,
  Contact,
  Check,
  ChevronDown,
  ChevronLeft,
  ChevronUp,
  ChevronsLeft,
  ChevronsRight,
  ChevronRight,
  ChevronsUpDown,
  Clock,
  Coins,
  Columns3,
  Cloud,
  Copy,
  CreditCard,
  Download,
  FileText,
  FolderTree,
  Gauge,
  History,
  ImagePlus,
  Info,
  KeyRound,
  Languages,
  LayoutDashboard,
  LockKeyhole,
  LogOut,
  Menu,
  MonitorSmartphone,
  Package,
  Paperclip,
  Palette,
  Pencil,
  Percent,
  Plus,
  Redo2,
  RefreshCw,
  Ruler,
  Search,
  Send,
  Share2,
  SquareCheckBig,
  Shapes,
  SlidersHorizontal,
  ShieldCheck,
  TabletSmartphone,
  Trash2,
  TriangleAlert,
  Truck,
  Undo2,
  Users,
  WifiOff,
  Workflow,
  X,
} from 'lucide-react'
import { cn } from '@/lib/utils'

const ICONS = {
  check: Check,
  x: X,
  filter: SlidersHorizontal,
  alert: TriangleAlert,
  info: Info,
  cloud: Cloud,
  sync: RefreshCw,
  offline: WifiOff,
  chevron: ChevronDown,
  clock: Clock,
  up: ArrowUp,
  down: ArrowDown,
  dashboard: LayoutDashboard,
  organisation: Building2,
  users: Users,
  roles: ShieldCheck,
  appearance: Palette,
  sessions: MonitorSmartphone,
  security: LockKeyhole,
  menu: Menu,
  signOut: LogOut,
  language: Languages,
  updown: ChevronsUpDown,
  plus: Plus,
  copy: Copy,
  download: Download,
  chevronRight: ChevronRight,
  back: ArrowLeft,
  device: TabletSmartphone,
  edit: Pencil,
  archive: Archive,
  restore: ArchiveRestore,
  remove: Trash2,
  key: KeyRound,
  currencies: Coins,
  exchangeRates: ArrowLeftRight,
  taxes: Percent,
  paymentMethods: CreditCard,
  dimensions: FolderTree,
  sharing: Share2,
  items: Package,
  categories: Shapes,
  units: Ruler,
  customers: Contact,
  suppliers: Truck,
  creditLimits: Gauge,
  history: History,
  image: ImagePlus,
  search: Search,
  chevronLeft: ChevronLeft,
  chevronUp: ChevronUp,
  first: ChevronsLeft,
  last: ChevronsRight,
  columns: Columns3,
  workflows: Workflow,
  undo: Undo2,
  redo: Redo2,
  bell: Bell,
  templates: FileText,
  deliveries: Send,
  approvals: SquareCheckBig,
  attach: Paperclip,
}

/** Lucide line icon: 1.5 stroke, 16px in navigation, 18px in tools. Decorative only. */
export function Icon({ name, size = 16, className, ...rest }) {
  const Glyph = ICONS[name]
  if (!Glyph) return null
  return <Glyph size={size} strokeWidth={1.5} aria-hidden="true" focusable="false" className={cn('shrink-0', className)} {...rest} />
}
