// Compiles design/tokens.json into dist/ (CSS variables, Tailwind 4 theme, Tailwind 3 preset, native themes).
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const here = path.dirname(fileURLToPath(import.meta.url));
const source = JSON.parse(readFileSync(path.resolve(here, '../../design/tokens.json'), 'utf8'));
const outDir = path.join(here, 'dist');

const THEMES = source.color.themes.map((t) => t.id);
const SELECTORS = {
  light: ':root',
  dark: '[data-theme="dark"], .dark',
  executive: '[data-theme="executive"]',
  warm: '[data-theme="warm"]',
};
const isAlias = (v) => typeof v === 'string' && /^\{[\w-]+\}$/.test(v);
const aliasName = (v) => v.slice(1, -1);

// Per-theme value lookup; a theme without its own value inherits light.
const pick = (value, theme) => (typeof value === 'string' ? value : (value[theme] ?? value.light));

const colors = source.color.tokens;
const spacing = source.spacing.tokens;
const radii = source.radius.tokens;
const shadows = source.shadow.tokens;
const families = Object.entries(source.type.families);
const styles = source.type.groups.flatMap((g) => g.styles);

function themeEntries(theme) {
  const out = [];
  for (const t of colors) out.push([t.name, pick(t.value, theme)]);
  for (const t of spacing) out.push([t.name, t.value]);
  for (const t of radii) out.push([t.name, t.value]);
  for (const t of shadows) out.push([t.name, pick(t.value, theme)]);
  for (const [name, value] of families) out.push([`font-${name}`, value]);
  for (const s of styles) {
    out.push([`text-${s.name}-size`, s.fontSize]);
    out.push([`text-${s.name}-line`, s.lineHeight]);
    out.push([`text-${s.name}-weight`, String(s.fontWeight)]);
    if (s.letterSpacing) out.push([`text-${s.name}-tracking`, s.letterSpacing]);
  }
  return out;
}

// Theme-independent families (spacing, radius, fonts, type) are emitted once under :root.
const themed = new Set([...colors, ...shadows].map((t) => t.name));
const themedOnlyEntries = (theme) => themeEntries(theme).filter(([n]) => themed.has(n));

function cssBlock(selector, entries) {
  const lines = entries.map(([n, v]) => `  --${n}: ${isAlias(v) ? `var(--${aliasName(v)})` : v};`);
  return `${selector} {\n${lines.join('\n')}\n}\n`;
}

const banner = '/* Generated by packages/tokens/build.mjs from design/tokens.json. Do not edit. */\n';

const tokensCss =
  banner +
  '\n' +
  THEMES.map((t) => cssBlock(SELECTORS[t], t === 'light' ? themeEntries(t) : themedOnlyEntries(t))).join('\n');

// Tailwind 4
const twLines = [];
twLines.push(
  '@theme {',
  '  --color-*: initial;',
  '  --spacing-*: initial;',
  '  --radius-*: initial;',
  '  --shadow-*: initial;',
  '  --font-*: initial;',
  '  --text-*: initial;',
  '}',
  '',
  '@theme inline {',
  '  --color-transparent: transparent;',
  '  --color-current: currentColor;',
);
for (const t of colors) twLines.push(`  --color-${t.name}: var(--${t.name});`);
twLines.push('  --spacing-0: 0px;', '  --spacing-px: 1px;');
for (const t of spacing) twLines.push(`  --spacing-${t.name.replace(/^space-/, '')}: var(--${t.name});`);
for (const t of radii) twLines.push(`  --${t.name}: var(--${t.name});`);
for (const t of shadows) twLines.push(`  --${t.name}: var(--${t.name});`);
for (const [name] of families) twLines.push(`  --font-${name}: var(--font-${name});`);
for (const s of styles) {
  twLines.push(
    `  --text-${s.name}: var(--text-${s.name}-size);`,
    `  --text-${s.name}--line-height: var(--text-${s.name}-line);`,
    `  --text-${s.name}--font-weight: var(--text-${s.name}-weight);`,
  );
  if (s.letterSpacing) twLines.push(`  --text-${s.name}--letter-spacing: var(--text-${s.name}-tracking);`);
}
twLines.push('}', '', '/* Generated by packages/tokens/build.mjs from design/tokens.json. Do not edit. */', '');
const tailwindCss = twLines.join('\n');

// Tailwind 3 preset (replaces the default theme)
const sp = { 0: '0px', px: '1px' };
for (const t of spacing) sp[t.name.replace(/^space-/, '')] = `var(--${t.name})`;
const preset = {
  theme: {
    colors: {
      transparent: 'transparent',
      current: 'currentColor',
      ...Object.fromEntries(colors.map((t) => [t.name, `var(--${t.name})`])),
    },
    spacing: sp,
    borderRadius: Object.fromEntries(radii.map((t) => [t.name.replace(/^radius-/, ''), `var(--${t.name})`])),
    boxShadow: Object.fromEntries(shadows.map((t) => [t.name.replace(/^shadow-/, ''), `var(--${t.name})`])),
    fontFamily: Object.fromEntries(families.map(([n]) => [n, `var(--font-${n})`])),
    fontSize: Object.fromEntries(
      styles.map((s) => {
        const extra = {
          lineHeight: `var(--text-${s.name}-line)`,
          fontWeight: `var(--text-${s.name}-weight)`,
        };
        if (s.letterSpacing) extra.letterSpacing = `var(--text-${s.name}-tracking)`;
        return [s.name, [`var(--text-${s.name}-size)`, extra]];
      }),
    ),
  },
};
const presetJs = `${banner}module.exports = ${JSON.stringify(preset, null, 2)};\n`;

// Native: literal values, aliases resolved per theme
const nativeThemes = {};
for (const theme of THEMES) {
  const byName = Object.fromEntries(themeEntries(theme));
  const resolve = (v) => {
    const seen = new Set();
    while (isAlias(v)) {
      const n = aliasName(v);
      if (seen.has(n) || !(n in byName)) throw new Error(`Bad alias ${v}`);
      seen.add(n);
      v = byName[n];
    }
    return v;
  };
  nativeThemes[theme] = Object.fromEntries(
    themeEntries(theme)
      .filter(([n]) => !shadows.some((s) => s.name === n))
      .map(([n, v]) => [`--${n}`, resolve(v)]),
  );
}
const nativeJs = `${banner}module.exports = ${JSON.stringify(nativeThemes, null, 2)};\n`;

mkdirSync(outDir, { recursive: true });
writeFileSync(path.join(outDir, 'tokens.css'), tokensCss);
writeFileSync(path.join(outDir, 'tailwind.css'), tailwindCss);
writeFileSync(path.join(outDir, 'tailwind-v3-preset.js'), presetJs);
writeFileSync(path.join(outDir, 'native-themes.js'), nativeJs);
writeFileSync(
  path.join(outDir, 'tokens.json'),
  JSON.stringify({ themes: Object.fromEntries(THEMES.map((t) => [t, nativeThemes[t]])) }, null, 2) + '\n',
);
